[package]
name = "debug_uget"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ureq = "2.8.0"
trust-dns-resolver = "0.23.2"
anyhow = "1"

[[bin]]
name = "resolve"